#!/usr/bin/env bash
# file-protection.sh
# PreToolUse hook for Write|Edit. Blocks edits to sensitive files
# (env files, lockfiles, .git internals, node_modules, local settings).
# Exit 2 = block; exit 0 = allow.

set -u

if ! command -v jq >/dev/null 2>&1; then
    # Without jq we can't parse — fail open.
    exit 0
fi

SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../scripts/lib.sh
. "$SOURCE_DIR/../scripts/lib.sh"

INPUT=$(cat 2>/dev/null || true)
FILE_PATH=$(printf '%s' "$INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null)

[ -n "$FILE_PATH" ] || exit 0

block() {
    printf '[flow file-protection] Blocked write to "%s": %s\n' "$FILE_PATH" "$1" >&2
    exit 2
}

# Project-configured secret globs (config: secret_globs) take precedence so the
# same patterns guard reads (secret-guard.sh) and writes.
if flow_path_is_secret "$FILE_PATH"; then
    block "matches a configured secret_globs pattern — edit manually"
fi

case "$FILE_PATH" in
    *.env|*.env.*|*/.env|*/.env.*)
        block "env files contain secrets — edit manually" ;;
    *package-lock.json|*pnpm-lock.yaml|*yarn.lock|*poetry.lock|*Cargo.lock|*Gemfile.lock|*composer.lock|*uv.lock)
        block "lockfiles must be regenerated by their package manager, not hand-edited" ;;
    */.git/*|*.git/*)
        block "git internals are off-limits" ;;
    */node_modules/*)
        block "node_modules is generated — edit the source instead" ;;
    */.claude/settings.local.json)
        block "local settings are user-specific and not for agent edits" ;;
esac

exit 0
